[package]
name = "exercism-solutions"
version = "0.0.1"
authors = [ "Mark Redeman <markredeman@gmail.com>" ]

[workspace]

members = [
"accumulate",
"acronym",
"affine-cipher",
"allergies",
"all-your-base",
"alphametics",
"anagram",
"armstrong-numbers",
"atbash-cipher",
"beer-song",
"binary-search",
"bob",
"book-store",
"bowling",
"circular-buffer",
"clock",
"collatz-conjecture",
"crypto-square",
"custom-set",
"decimal",
"diamond",
"difference-of-squares",
"diffie-hellman",
"dominoes",
"dot-dsl",
"doubly-linked-list",
"eliuds-eggs",
"etl",
"fizzy",
"forth",
"gigasecond",
"grade-school",
"grains",
"grep",
"hamming",
"hello-world",
"high-scores",
"isbn-verifier",
"isogram",
"kindergarten-garden",
"knapsack",
"largest-series-product",
"leap",
"luhn",
"luhn-from",
"luhn-trait",
"macros",
"matching-brackets",
"matrix",
"minesweeper",
"nth-prime",
"nucleotide-count",
"ocr-numbers",
"paasio",
"palindrome-products",
"pangram",
"parallel-letter-frequency",
"pascals-triangle",
"perfect-numbers",
"phone-number",
"pig-latin",
"poker",
"prime-factors",
"protein-translation",
"proverb",
"pythagorean-triplet",
"queen-attack",
"rail-fence-cipher",
"raindrops",
"react",
"rectangles",
"reverse-string",
"rna-transcription",
"robot-name",
"robot-simulator",
"roman-numerals",
"rotational-cipher",
"run-length-encoding",
"saddle-points",
"say",
"scrabble-score",
"secret-handshake",
"series",
"sieve",
"simple-cipher",
"simple-linked-list",
"space-age",
"spiral-matrix",
"sublist",
"sum-of-multiples",
"tournament",
"triangle",
"two-bucket",
"variable-length-quantity",
"wordy",
"word-count",
"xorcism",
"yacht"
]
